version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "file:/usr/src/app/prisma/dev.db"
